{
 "title": "device",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataPath": "parameters.gps_data.Latitude",
     "label": "Latitude",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Latitude",
     "type": "notification"
    },
    {
     "dataPath": "parameters.gps_data.Longitude",
     "label": "Longitude",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Longitude",
     "type": "notification"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataPath": "parameters.gps_data.Altitude",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "notificationA",
     "type": "notification"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataPath": "parameters.macaddress1.movement[0].x",
     "label": "Accel x",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Accel x",
     "type": "notification"
    },
    {
     "dataPath": "parameters.macaddress1.movement[0].y",
     "label": "Accel y",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Accel y",
     "type": "notification"
    },
    {
     "dataPath": "parameters.macaddress1.movement[0].z",
     "label": "Accel z",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Accel z",
     "type": "notification"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "dataPath": "parameters.gps_data.Speed",
     "label": "Speed",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Speed",
     "type": "notification"
    }
   ]
  },
  {
   "title": "Movement",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataPath": "parameters.macaddress1.movement[0].status",
     "label": "Sensor status (ON/OFF)",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Sensor status (ON/OFF)",
     "type": "notification"
    },
    {
     "dataPath": "parameters.macaddress1.movement[0].movement",
     "label": "Movement detected (YES/NO)",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Movement detected (YES/NO)",
     "type": "notification"
    }
   ]
  },
  {
   "title": "Hit detection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataPath": "parameters.macaddress1.hit[0].status",
     "label": "Sensor status (ON/OFF)",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Sensor status (ON/OFF)",
     "type": "notification"
    },
    {
     "dataPath": "parameters.macaddress1.hit[0].hit",
     "label": "Hit detected (YES/NO)",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Hit detected (YES/NO)",
     "type": "notification"
    }
   ]
  },
  {
   "title": "Door",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataPath": "parameters.macaddress1.door[0].status",
     "label": "Sensor status (ON/OFF)",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Sensor status (ON/OFF)",
     "type": "notification"
    },
    {
     "dataPath": "parameters.macaddress1.door[0].door_state",
     "label": "Door status (OPEN/CLOSED)",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Door status (OPEN/CLOSED)",
     "type": "notification"
    }
   ]
  },
  {
   "title": "Light Status (ON/OFF)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataPath": "parameters.macaddress1.light[0].status",
     "label": "Light status ()",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "Light status ()",
     "type": "notification"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "valueName": "total",
   "targets": [
    { "target": "notificationA", "type": "notification" }
   ]
  },
  {
   "title": "UTC",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "UTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataPath": "parameters.gps_data.UTC",
     "name": "7owB9W6exKuJ0S4WMYs6ylqac5E4oeMUwPXo",
     "target": "notificationA",
     "type": "notification"
    }
   ]
  }
 ]
}